# Generated by Django 3.2 on 2021-04-25 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=7)),
                ('memory', models.CharField(max_length=7)),
                ('display', models.CharField(max_length=10)),
                ('gpu', models.CharField(max_length=20)),
                ('cpu', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=7)),
                ('recieveddate', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('imgurl', models.CharField(blank=True, max_length=40, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_phone',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=21)),
                ('surname', models.CharField(max_length=20)),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('age', models.SmallIntegerField()),
                ('registrationdate', models.DateField()),
                ('imgurl', models.CharField(blank=True, max_length=40, null=True)),
                ('role', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'user_table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('userid', models.OneToOneField(db_column='userid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='AngularShop.usertable')),
                ('amount', models.IntegerField()),
                ('phoneid', models.ForeignKey(db_column='phoneid', on_delete=django.db.models.deletion.DO_NOTHING, to='AngularShop.appphone')),
            ],
            options={
                'db_table': 'cart',
                'managed': True,
                'unique_together': {('userid', 'phoneid')},
            },
        ),
    ]
