# Generated by Django 3.2 on 2021-04-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AngularShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='role',
            field=models.CharField(blank=True, default='U', max_length=2, null=True),
        ),
    ]
